// ---------- v47: KAHRAMANIN ÖZEL GÜÇLERİ ----------
/* Ok Yağmuru: en kalabalık düşman kümesine gökten ok yağar (geniş alan, büyük hasar, geri savurma).
   Hücum: kahraman koştuğu yöne atılır, yolundaki düşmanları vurup iki yana savurur.
   Bekleme süresi var: doğru anda basmak beceri ister. Dokunmatikte iki büyük düğme, klavyede Q ve E. */
const SK={rain:{cd:14,t:0,ic:'🏹',n:T('Ok Yağmuru','Arrow Rain'),key:'Q'},dash:{cd:7,t:0,ic:'⚡',n:T('Hücum','Charge'),key:'E'}};
let dashT=0; const dashU=[0,1]; const dashHit=new Set(); const rains=[]; let skUI=null, skSeen=false;
function skillDmg(){ return D.heroDmg()*(1+0.04*Math.floor(hlv()/5)); }
function rainTarget(){ const p=player.g.position; let best=null, bn=0; for(const e of allFoes()){ if(e.dead||e.hold) continue; const d=Math.hypot(e.g.position.x-p.x,e.g.position.z-p.z); if(d>19) continue; let n=0; for(const o of allFoes()){ if(o.dead) continue; if(Math.hypot(o.g.position.x-e.g.position.x,o.g.position.z-e.g.position.z)<4.6) n+=o.boss?3:1; } if(n>bn){ bn=n; best=e; } } return best?[best.g.position.x,best.g.position.z]:null; }
function skillReady(k){ return SK[k].t<=0&&!runOver; }
function useRain(){ if(!skillReady('rain')) return false; const at=rainTarget(); if(!at){ toast(T('Yakında düşman yok','No enemies nearby'),''); return false; } SK.rain.t=SK.rain.cd;
  const ring=new THREE.Mesh(new THREE.RingGeometry(RAIN_R-0.4,RAIN_R+0.1,40).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color:0xffd23f,transparent:true,opacity:0.9,depthWrite:false})); ring.position.set(at[0],0.08,at[1]); ring.renderOrder=4; scene.add(ring);
  const arrows=[]; for(let i=0;i<22;i++){ const g=new THREE.Group(); const sh=new THREE.Mesh(HA_GEO.shaft,HA_MAT.shaft), hd=new THREE.Mesh(HA_GEO.head,HA_MAT.head); g.add(sh,hd); const a=Math.random()*6.283, r=Math.sqrt(Math.random())*(RAIN_R-0.2); g.userData={x:at[0]+Math.cos(a)*r,z:at[1]+Math.sin(a)*r,d:0.12+Math.random()*0.35}; g.position.set(g.userData.x-3,14,g.userData.z-3); g.lookAt(g.userData.x,0,g.userData.z); g.visible=false; g.scale.setScalar(1.3); scene.add(g); arrows.push(g); }
  rains.push({x:at[0],z:at[1],t:0,ring,arrows,hit:false}); try{ SFX.bow(); setTimeout(()=>{ try{ SFX.bow(); }catch(e){} },90); }catch(e){} player.shot=1; skillUsed('rain'); return true; }
function useDash(){ if(!skillReady('dash')) return false; const inp=inputVec(); let ux=inp.x, uz=inp.z; if(inp.l<0.1){ const ry=player.g.rotation.y; ux=Math.sin(ry); uz=Math.cos(ry); const e=nearestEnemy(player.g.position,9); if(e){ const dx=e.g.position.x-player.g.position.x, dz=e.g.position.z-player.g.position.z, d=Math.hypot(dx,dz)||1; ux=dx/d; uz=dz/d; } } const l=Math.hypot(ux,uz)||1; dashU[0]=ux/l; dashU[1]=uz/l;
  SK.dash.t=SK.dash.cd; dashT=0.3; dashHit.clear(); player.g.rotation.y=Math.atan2(dashU[0],dashU[1]); player.swing=0.3; try{ tone(180,520,0.18,'sawtooth',0.05); noise(0.15,0.12); }catch(e){} skillUsed('dash'); return true; }
function skillUsed(k){ if(S.meta){ S.meta.skUse=S.meta.skUse||{}; S.meta.skUse[k]=(S.meta.skUse[k]|0)+1; } }
function dashMul(){ return dashT>0?3.4:1; }
function updateSkills(dt){ for(const k in SK) SK[k].t=Math.max(0,SK[k].t-dt);
  if(dashT>0){ dashT-=dt; const p=player.g.position; if(Math.random()<0.7) burst(p.clone().setY(0.3),1,M.trunk,0.3); for(const e of allFoes()){ if(e.dead||dashHit.has(e)) continue; const ep=e.g.position; const dx=ep.x-p.x, dz=ep.z-p.z, d=Math.hypot(dx,dz); if(d>1.9*(e.rad||1)) continue; dashHit.add(e); damageEnemy(e,skillDmg()*2.4,'sword'); spark(ep.x,1.1*(e.sc||1),ep.z,8,1.3); if(!e.dead&&!e.boss&&e.kind!=='ram'){ const side=(dx*dashU[1]-dz*dashU[0])>=0?1:-1; ep.x+=dashU[1]*side*1.8+dashU[0]*0.6; ep.z+=-dashU[0]*side*1.8+dashU[1]*0.6; } camShake=Math.max(camShake,0.18); } }
  for(let i=rains.length-1;i>=0;i--){ const r=rains[i]; r.t+=dt; r.ring.material.opacity=0.9*(1-Math.max(0,r.t-0.7)/0.5); r.ring.scale.setScalar(1+0.06*Math.sin(r.t*20));
    for(const a of r.arrows){ const u=a.userData; const k=(r.t-u.d)/0.32; if(k<0) continue; a.visible=k<1.25; const kk=Math.min(1,k); a.position.set(u.x-3*(1-kk),14*(1-kk)+0.4,u.z-3*(1-kk)); }
    if(!r.hit&&r.t>0.5){ r.hit=true; camShake=Math.max(camShake,0.38); try{ noise(0.3,0.22); tone(140,60,0.3,'sawtooth',0.06); }catch(e){} burst(new THREE.Vector3(r.x,0.4,r.z),14,M.trunk,1.1); let n=0;
      for(const e of allFoes()){ if(e.dead) continue; const ep=e.g.position; const dx=ep.x-r.x, dz=ep.z-r.z, d=Math.hypot(dx,dz); if(d>RAIN_R+0.2+(e.rad||1)*0.5) continue; damageEnemy(e,skillDmg()*(e.boss?2.2:3.6),'sword'); n++; spark(ep.x,1,ep.z,5,1); if(!e.dead&&!e.boss&&e.kind!=='ram'&&d>0.01){ ep.x+=dx/d*1.4; ep.z+=dz/d*1.4; } }
      if(n>=4) floatText(new THREE.Vector3(r.x,2.5,r.z),'×'+n,'big'); }
    if(r.t>1.3){ scene.remove(r.ring); r.ring.geometry.dispose(); r.ring.material.dispose(); for(const a of r.arrows) scene.remove(a); rains.splice(i,1); } }
  skillUI(); hlvHud(); }
/* düğmeler: sağ altta (mini haritanın üstünde), bekleme halkası */
function skillUI(){ if(!skUI){ const box=document.createElement('div'); box.id='skills'; box.style.cssText='position:fixed;right:max(14px,env(safe-area-inset-right));bottom:calc(env(safe-area-inset-bottom) + 160px);display:flex;flex-direction:column;gap:12px;z-index:6;user-select:none;-webkit-user-select:none';
    const mk=k=>{ const b=document.createElement('button'); b.className='skbtn'; b.dataset.k=k; b.style.cssText='position:relative;width:70px;height:70px;border-radius:50%;border:3px solid #fff;background:#2a3346;color:#fff;font-size:30px;line-height:1;box-shadow:0 4px 0 rgba(0,0,0,.35),0 0 0 3px rgba(0,0,0,.15);touch-action:none;padding:0;cursor:pointer;overflow:hidden';
      b.innerHTML=`<i style="position:absolute;inset:0;border-radius:50%;pointer-events:none"></i><span style="position:relative">${SK[k].ic}</span><small style="position:absolute;left:0;right:0;bottom:7px;font:800 10px var(--font-display,sans-serif);letter-spacing:.3px;pointer-events:none">${isTouch?'':SK[k].key}</small>`;
      const go=ev=>{ ev.preventDefault(); ev.stopPropagation(); audio(); if(k==='rain') useRain(); else useDash(); }; b.addEventListener('pointerdown',go); b.addEventListener('touchstart',ev=>ev.stopPropagation(),{passive:true}); return b; };
    box.appendChild(mk('rain')); box.appendChild(mk('dash')); document.body.appendChild(box); skUI={box,b:[...box.children]};
    addEventListener('keydown',ev=>{ if(ev.repeat||!started) return; const k=ev.key.toLowerCase(); if(k==='q'||k==='1') useRain(); else if(k==='e'||k==='2') useDash(); }); }
  const show=started&&!runOver&&!document.querySelector('.intro:not(#intro)')&&(S.wave>=1)&&(waveActive||S.level>1||S.wave>1||skSeen); skUI.box.style.display=show?'flex':'none'; if(waveActive&&!skSeen){ skSeen=true; setTimeout(()=>{ if(!runOver) toast(isTouch?T('🏹 Ok Yağmuru ve ⚡ Hücum hazır: sağdaki düğmeler','🏹 Arrow Rain and ⚡ Charge are ready: buttons on the right'):T('🏹 Ok Yağmuru: Q · ⚡ Hücum: E','🏹 Arrow Rain: Q · ⚡ Charge: E'),'gold'); },1200); }
  for(const b of skUI.b){ const s=SK[b.dataset.k]; const f=s.t/s.cd; const ring=b.firstChild; if(f>0){ ring.style.background=`conic-gradient(rgba(10,14,22,.72) ${Math.round(f*360)}deg, transparent 0)`; b.style.borderColor='#8a93a6'; b.style.transform=''; } else { ring.style.background=''; b.style.borderColor='#ffd23f'; const near=nearestEnemy(player.g.position,b.dataset.k==='rain'?19:9); b.style.transform=near&&waveActive?`scale(${1+0.06*Math.sin(performance.now()/160)})`:''; } } }
function resetSkills(){ for(const k in SK) SK[k].t=0; dashT=0; for(const r of rains){ scene.remove(r.ring); for(const a of r.arrows) scene.remove(a); } rains.length=0; }
/* v47: KAHRAMAN SEVİYESİ (kalıcı, haritalar arası): her öldürme deneyim verir; seviye atlayınca kahraman güçlenir (+%3 ok hasarı), belli seviyelerde güçler büyür.
   Sol üstte yıldız rozeti + dolan çubuk: savaşırken hep bir sonraki seviyeye az kalmış hissi */
function hlv(){ return (S.meta&&S.meta.hlv)|0||1; }
function xpNeed(l){ return Math.round(22+14*Math.pow(l,1.3)); }
function heroLvK(){ return 1+0.03*(hlv()-1); }
let hlvUI=null, hlvShown=-1;
function heroXP(e){ if(!S.meta) return; const m=S.meta; if(!m.hlv) m.hlv=1; const g=e.boss?25:e.camp?(e.sc>1.2?6:2):(e.kind==='knight'||e.kind==='shield'||e.kind==='ram')?2:1; m.hxp=(m.hxp|0)+g; let up=0; while(m.hxp>=xpNeed(m.hlv)&&m.hlv<60){ m.hxp-=xpNeed(m.hlv); m.hlv++; up++; } if(up) heroLevelUp(); }
function heroLevelUp(){ const l=hlv(); try{ SFX.fanfare(); }catch(e){} const p=player.g.position; celebrate(p.clone(),0.9); burst(p.clone().setY(1.6),14,M.gold,1.4,0.9); let extra=''; if(l===3) extra=T(' · 🏹 Ok Yağmuru genişledi',' · 🏹 Arrow Rain wider'); else if(l===5) extra=T(' · ⚡ Hücum daha sık',' · ⚡ Charge recharges faster'); else if(l===8) extra=T(' · 🏹 Ok Yağmuru daha sık',' · 🏹 Arrow Rain recharges faster'); else if(l%5===0) extra=T(' · güçler daha sert vuruyor',' · skills hit harder');
  toast(T(`⭐ Kahraman Sv. ${l}! Okların +%3 güçlendi`,`⭐ Hero Lv ${l}! Arrows +3% stronger`)+extra,'gold'); skillScale(); save(); }
function skillScale(){ const l=hlv(); SK.dash.cd=l>=5?5.5:7; SK.rain.cd=l>=8?11:14; RAIN_R=l>=3?5.4:4.6; }
let RAIN_R=4.6;
function hlvHud(){ if(!hlvUI){ const left=document.querySelector('#hud .left')||document.querySelector('.left'); if(!left) return; const c=document.createElement('div'); c.className='chip'; c.id='hlvChip'; c.style.cssText='gap:6px;padding-right:10px'; c.innerHTML='<b style="font:800 15px var(--font-display,sans-serif);white-space:nowrap">⭐ <span id="hlvN">1</span></b><span style="display:block;width:46px;height:7px;border-radius:5px;background:rgba(0,0,0,.18);overflow:hidden"><i id="hlvBar" style="display:block;height:100%;width:0;background:linear-gradient(90deg,#ffd23f,#ff9f1a);border-radius:5px"></i></span>'; const cc=left.querySelector('#coinChip'); if(cc&&cc.nextSibling) left.insertBefore(c,cc.nextSibling); else left.appendChild(c); hlvUI={n:c.querySelector('#hlvN'),bar:c.querySelector('#hlvBar')}; skillScale(); }
  const l=hlv(); if(l!==hlvShown){ hlvShown=l; hlvUI.n.textContent=l; } hlvUI.bar.style.width=Math.round(100*Math.min(1,((S.meta&&S.meta.hxp)|0)/xpNeed(l)))+'%'; }
