// ---------- v47: İSKELET KAMPLARI — kaleden çıkmak için sebep ----------
/* Her haritada ilk geceden sonra her gündüz kale dışında (ormanda) bir iskelet kampı kurulur: çadır, ateş, ganimet sandığı ve 3-6 nöbetçi.
   Nöbetçiler yürümez; kahraman yaklaşınca saldırır. Kahramana vuran nöbetçi sırtındaki altından düşürür (yerden geri toplanır) — risk.
   Hepsi ölünce sandık açılır: büyük altın (+ bazen 👑). Kamp geceleri de yerinde kalır, nöbetçiler kaleye yürümez. */
const campFoes=[]; let skc=null, campSeq=0;
function allFoes(){ return campFoes.length?enemies.concat(campFoes):enemies; }
function campValue(){ return Math.round((70+45*(S.level|0))*(1+0.25*Math.max(0,(S.wave|0)-2))); }
function campSpot(){ const rnd=thRng((S.level|0)*977+(S.wave|0)*131+(++campSeq)*17); const tk=themeObs.map(o=>[o[0],o[1],o[2]]); const sp=findSpots(rnd,1,4.2,tk,themeHm()+9,themeHm()+21); return sp[0]||null; }
function spawnCamp(){ if(skc||!MAPS[S.level]&&S.level<=LEVELS) return; const at=campSpot(); if(!at) return; const [x,z]=at; const g=new THREE.Group(); g.position.set(x,0,z); scene.add(g);
  /* çadır, ateş, kemik bayrak, sandık */ if(artOk()&&ART.glb.bld){ const t=artProp('tent',4.2); if(t){ t.position.set(-1.6,0,-1.4); t.rotation.y=0.6; g.add(t); } for(const [px,pz,n] of [[1.9,-1.2,'barrel'],[2.3,-0.4,'crate_A_big'],[-2.4,1.2,'weaponrack']]){ const p=artProp(n,3.2); if(p){ p.position.set(px,0,pz); g.add(p); } } }
  else { const t=mesh(G.cone4,mat(0x5a3a2a),1.8,1.8,1.8); t.position.set(-1.6,0.9,-1.4); g.add(t); }
  const fire=new THREE.Group(); for(let i=0;i<6;i++){ const a=i/6*6.283; const st=mesh(G.dod,M.rock,0.22,0.16,0.22); st.position.set(Math.cos(a)*0.55,0.1,Math.sin(a)*0.55); fire.add(st); } const fl=mesh(G.cone,mat(0xff8a2a,{emissive:0xff5a10}),0.35,0.8,0.35,false); fl.position.y=0.45; fire.add(fl); fire.position.set(0.4,0,0.6); g.add(fire);
  const pole=mesh(G.cyl,M.woodDark,0.06,3.2,0.06); pole.position.set(-0.3,1.6,-2.2); const flag=mesh(G.box,mat(0x2a1a1a),0.9,0.65,0.04,false); flag.position.set(0.15,2.8,-2.2); const skull=mesh(G.sph,mat(0xe8e0d0),0.18,0.18,0.18,false); skull.position.set(0.15,2.8,-2.16); g.add(pole,flag,skull);
  const chest=new THREE.Group(); const body=mesh(G.box,M.chest,1.3,0.75,0.9); body.position.y=0.38; const lid=new THREE.Group(); lid.position.set(0,0.75,-0.45); const lm=mesh(G.box,M.chest,1.3,0.32,0.9); lm.position.set(0,0.16,0.45); lid.add(lm); for(const sx of [-0.4,0.4]){ const s1=mesh(G.box,M.gold,0.12,0.78,0.92,false); s1.position.set(sx,0.38,0); chest.add(s1); } chest.add(body,lid); chest.position.set(1.4,0,1.6); chest.rotation.y=-0.5; g.add(chest);
  const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:torchTex,color:0xffc040,transparent:true,opacity:0.5,depthWrite:false,blending:THREE.AdditiveBlending})); glow.scale.set(3.4,3.4,3.4); glow.position.set(1.4,1.0,1.6); g.add(glow);
  /* kamp yerindeki ağaçlar */ let a=false; trees.forEach((t,i)=>{ if(t.gone) return; if(Math.hypot(t.x-x,t.z-z)<7.5){ t.gone=true; t.culled=true; t.alive=false; t.claimed=null; writeTree(i); a=true; } }); if(a){ treeTrunk.instanceMatrix.needsUpdate=true; treeCrown.instanceMatrix.needsUpdate=true; }
  const n=Math.min(7,4+Math.floor(((S.level|0)+(S.wave|0))/3)); const kinds=['grunt','raider','shield','archer','knight']; const foes=[];
  for(let i=0;i<n;i++){ const k=i===0?((S.level|0)>=3?'knight':'shield'):kinds[Math.min(kinds.length-1,Math.floor(Math.random()*Math.min(kinds.length,1+(S.level|0)/2)))]; makeEnemy(k,'N'); const e=enemies.pop(); const ang=i/n*6.283+0.4, r=2.6+Math.random()*0.8; e.g.position.set(x+Math.cos(ang)*r,0,z+Math.sin(ang)*r); e.g.rotation.y=Math.atan2(-Math.cos(ang),-Math.sin(ang)); const chief=i===0; e.hp=e.maxHp=Math.round(e.maxHp*(chief?7:3)); if(chief){ e.g.scale.multiplyScalar(1.35); e.sc=(e.sc||1)*1.35; e.rad=(e.rad||1)*1.3; if(e.bar){ e.bar.classList.add('boss'); } } e.camp={x,z,home:[e.g.position.x,e.g.position.z],ag:false,cd:rand(0.4,1.2)}; if(e.bar) e.bar.style.display='none'; campFoes.push(e); foes.push(e); }
  skc={x,z,g,chest,lid,glow,fire:fl,open:0,val:campValue(),n,t:0}; if(S.started&&(S.wave|0)>=2&&!S.meta.campSeen){ S.meta.campSeen=1; setTimeout(()=>{ if(!runOver) toast(T('💀 Ormanda iskelet kampı! Yağmala, sandık senin','💀 A skeleton camp in the woods! Raid it, the chest is yours'),'gold'); },1500); } }
function campTarget(){ return skc&&!skc.open?new THREE.Vector3(skc.x,0,skc.z):null; }
function heroHurt(e){ const p=player.g.position; const carry=Math.floor(S.coins); pHitT=Math.max(pHitT||0,0.45); camShake=Math.max(camShake,0.2); try{ tone(220,90,0.15,'square',0.05); }catch(_){} if(carry<=0) return; const lose=Math.min(carry,Math.max(3,Math.round(carry*0.08))); S.coins-=lose; const n=Math.min(8,Math.max(2,Math.round(lose/6))); dropCoins(p.clone().setY(1.2),n,lose/n,3.2,1,0); floatText(p.clone().setY(2.6),'-'+lose,'red'); renderHud(); }
function updateCamp(dt){ if(!skc){ if(!waveActive&&(S.wave|0)>=2&&!runOver&&S.started&&!modalOpen()&&waveT>20&&(MAPS[S.level]||S.level>LEVELS)) spawnCamp(); return; }
  skc.t+=dt; skc.fire.scale.y=0.8+0.25*Math.sin(skc.t*11); const p=player.g.position;
  for(let i=campFoes.length-1;i>=0;i--){ const e=campFoes[i]; if(e.dead){ campFoes.splice(i,1); continue; } if(e.flashT>0){ e.flashT-=dt; if(e.flashT<=0) flashOff(e); } const C=e.camp, ep=e.g.position; const dh=Math.hypot(p.x-ep.x,p.z-ep.z), dc=Math.hypot(p.x-skc.x,p.z-skc.z);
    if(!C.ag&&(dh<9||e.hp<e.maxHp)){ C.ag=true; for(const o of campFoes) if(Math.hypot(o.g.position.x-ep.x,o.g.position.z-ep.z)<8) o.camp.ag=true; }
    if(C.ag&&dc>24){ C.ag=false; e.hp=e.maxHp; } /* kahraman uzaklaşınca dönerler ve iyileşirler */
    let tx=C.home[0], tz=C.home[1], moving=false; if(C.ag){ tx=p.x; tz=p.z; }
    const dx=tx-ep.x, dz=tz-ep.z, d=Math.hypot(dx,dz); const reach=C.ag?1.25*(e.rad||1):0.2;
    if(d>reach){ const sp=Math.min(d,e.speed*0.85*dt); ep.x+=dx/d*sp; ep.z+=dz/d*sp; e.g.rotation.y=Math.atan2(dx,dz); moving=true; }
    else if(C.ag){ e.g.rotation.y=Math.atan2(dx,dz); C.cd-=dt; if(C.cd<=0){ C.cd=1.15; if(e.guy) e.guy.swing=0.3; setTimeout(()=>{ if(!e.dead&&Math.hypot(player.g.position.x-e.g.position.x,player.g.position.z-e.g.position.z)<2.2) heroHurt(e); },260); } }
    for(const o of campFoes){ if(o===e||o.dead) continue; const ox=ep.x-o.g.position.x, oz=ep.z-o.g.position.z, od=Math.hypot(ox,oz); if(od<1.0&&od>0.001){ ep.x+=ox/od*(1.0-od)*0.5; ep.z+=oz/od*(1.0-od)*0.5; } }
    animEnemy(e,dt,moving); }
  if(!skc.open&&campFoes.length===0){ skc.open=0.001; /* sandık açılır */ SFX.fanfare(); camShake=Math.max(camShake,0.3); const v=skc.val; const at=skc.chest.getWorldPosition(new THREE.Vector3()).setY(1.2); dropCoins(at,16,v/16,4,1.3,1); let cr=0; if(Math.random()<0.35+0.05*(S.level|0)){ cr=1; S.meta.crowns=(S.meta.crowns|0)+1; } celebrate(at,1.2); banner(T('Kamp yağmalandı!','Camp raided!'),T(`💰 +${v} altın`,`💰 +${v} gold`)+(cr?' · 👑 +1':''),'day'); questEvent('camp',1); S.campsRaided=(S.campsRaided|0)+1; save(); }
  if(skc.open>0){ skc.open+=dt; skc.lid.rotation.x=-Math.min(1.9,skc.open*4); skc.glow.material.opacity=Math.max(0,0.8-skc.open*0.3); if(skc.open>14&&Math.hypot(p.x-skc.x,p.z-skc.z)>30){ clearCamp(); } } }
function clearCamp(){ if(skc){ scene.remove(skc.g); skc=null; } for(const e of campFoes){ scene.remove(e.g); if(e.bar) e.bar.remove(); } campFoes.length=0; }
